Fix Flake8 issues, #23
ConstellationApps/TicketBox pull request #25
Opened 2017-04-08 00:51 UTC by tdorianh

2017-04-09 23:45 UTC, the-maldridge requested changes
Lots of places are  casting to lists with commas that are not always necessary.  If you do not have another item in the list, there should be no comma and no space after the list element.

2017-04-09 23:45 UTC, the-maldridge commented on constellation_ticketbox/forms.py
> +        fields = ['title', 'body', 'anonymous', 'status', ]
If there is no next element, the list should not have a continuation comma.

2017-04-09 23:45 UTC, the-maldridge commented on constellation_ticketbox/models.py
>      STATUS_CHOICES = (
Why is this an enum?  Why can't these just be strings?

2017-04-09 23:45 UTC, the-maldridge commented on constellation_ticketbox/tests.py
> -from django.test import TestCase
If you have no tests this file should be removed.

2017-04-09 23:45 UTC, the-maldridge commented on constellation_ticketbox/urls.py
> +    # =============================================================================
This should be left aligned to match the rest of the constellation suite.

2017-04-09 23:45 UTC, the-maldridge commented on constellation_ticketbox/urls.py
> +    # =============================================================================
Left align

2017-04-09 23:45 UTC, the-maldridge commented on constellation_ticketbox/urls.py
> +    # =============================================================================
Left Align

2017-04-09 23:45 UTC, the-maldridge commented on constellation_ticketbox/urls.py
> +    # -----------------------------------------------------------------------------
Left align

2017-04-09 23:45 UTC, the-maldridge commented on constellation_ticketbox/urls.py
> +    # -----------------------------------------------------------------------------
Left align

2017-04-09 23:45 UTC, the-maldridge commented on constellation_ticketbox/urls.py
> +    # -----------------------------------------------------------------------------
Left align

2017-04-09 23:45 UTC, the-maldridge commented on constellation_ticketbox/urls.py
> +    # -----------------------------------------------------------------------------
Left align

2017-04-09 23:45 UTC, the-maldridge commented on constellation_ticketbox/views.py
> -                    archived=False)
I am having trouble believing that this is flake8 compliant indentation.

2017-04-09 23:45 UTC, the-maldridge commented on constellation_ticketbox/views.py
> +                                          archived=True)
indentation...

2017-04-09 23:45 UTC, the-maldridge commented on constellation_ticketbox/views.py
> +        if (newTicket.anonymous is False):
an explicit check for False here is not needed.  Check for not newTicket.anonymous instead.

2017-04-09 23:45 UTC, the-maldridge commented on constellation_ticketbox/views.py
> +        return HttpResponseNotFound("You do not have permissions " +
These lines will be joined implicitly, there is no need for the '+'

2017-04-09 23:45 UTC, the-maldridge commented on constellation_ticketbox/views.py
> +                ('action_manage_tickets' in box_perms)):
over indented.

2017-04-09 23:45 UTC, the-maldridge commented on constellation_ticketbox/views.py
> +                if (ticket.owner is request.user and ticket.archived is True):
ticket.archived is already True on its own, this comparison is unnecessary.

2017-04-09 23:45 UTC, the-maldridge commented on constellation_ticketbox/views.py
> +                if (ticket.anonymous is True and ticket.owner is request.user):
Unnecessary comparison to literal.

2017-04-09 23:45 UTC, the-maldridge commented on constellation_ticketbox/views.py
> +            if (ticket.anonymous is True and request.user is ticket.owner):
Unnecessary literal comparison

2017-04-09 23:45 UTC, the-maldridge commented on constellation_ticketbox/views.py
> +                return HttpResponseServerError("Could not save reply" +
Unnecessary explicit line join

2017-04-09 23:45 UTC, the-maldridge commented on constellation_ticketbox/views.py
> +        return HttpResponseBadRequest("You don't have permissions " +
Unnecessary explicit line join

2017-04-09 23:45 UTC, the-maldridge commented on constellation_ticketbox/views.py
> +            return HttpResponseBadRequest("You don't have permissions " +
Unnecessary explicit line join

2017-04-09 23:45 UTC, the-maldridge commented on constellation_ticketbox/views.py
> +        if ((ticket.owner == request.user) or
Comparison of objects using `==` instead of `is`

2017-04-09 23:45 UTC, the-maldridge commented on constellation_ticketbox/views.py
> +        return HttpResponseNotFound("You do not have permissions " +
Lines are already implicitly joined.

2017-04-09 23:45 UTC, the-maldridge commented on constellation_ticketbox/forms.py
> +
There should be a docstring here

2017-04-09 23:45 UTC, the-maldridge commented on constellation_ticketbox/forms.py
> +
There should be a docstring here

2017-04-10 00:55 UTC, tdorianh commented on constellation_ticketbox/views.py
> +        if ((ticket.owner == request.user) or
For some reason using `is` will cause this test to always fail, but it has the correct functionality using `==`.

2017-04-10 01:32 UTC, tdorianh commented on constellation_ticketbox/models.py
>      STATUS_CHOICES = (
Status is currently used to determine whether or not a ticket should be archived upon status update. 

Should this be changed to require an explicit archiving when a ticket status is updated, and allow users to enter anything into the status field?

2017-04-10 20:59 UTC, tdorianh commented
Commit 04dcd04 removes the previous method of archiving tickets by selecting statuses from a limited list. In this version, archiving and status updates are separate buttons, allowing managing groups to update a status without changing the open/closed archive state of the ticket (such as for status messages like "In progress"). Status is also now simply strings. A button on the ticket page has been added for archiving and unarchiving.

2017-04-11 03:56 UTC, merged